cfehome/src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import (
	ItemListView,
    ItemCreateView,
    ItemDetailView,
    ItemUpdateView
)

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(),name="create"),
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name="edit"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name="detail"),
    url(r'^$', ItemListView.as_view(),name="list"),
]

cfehome/src/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

cfehome/src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ forms.error.non_field_errors}}
{% endif %}
<form method="POST">{% csrf_token %}
	{{form.as_p}}
	<button type="submit">Save</button>
</form>

cfehome/src/templates/snippets/js.html
<script type="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

cfehome/src/templates/snippets/nav.html
<div class="container">
	<h1>muypicky.com</h1>
	<a href="{% url 'home' %}">home</a>
	<a href="{% url 'about' %}">About</a>
	<a href="{% url 'contact' %}">Contact</a>
	{% if request.user.is_authenticated%}
	<a href="{% url 'restaurants:list' %}">Restaurants</a>
	<a href="{% url 'menus:list' %}">Menu Items</a>
	{% endif %}
</div>

cfehome/src/templates/snippets/sidebar.html
<ul>
	<li>item1</li>
	<li>item2</li>
	<li>item3</li>
</ul>